from typing import Literal, Type, Union, Optional, overload
from deeplay.components import ConvolutionalEncoder2d

__all__ = ['CycleGANDiscriminator']

class CycleGANDiscriminator(ConvolutionalEncoder2d):
    @overload
    def style(self, style: Literal["resnet18"], ) -> Self: ...
    @overload
    def style(self, style: Literal["cyclegan_resnet_encoder"], ) -> Self: ...
    @overload
    def style(self, style: Literal["cyclegan_discriminator"], ) -> Self: ...
    @overload
    def style(self, style: Literal["dcgan_discriminator"], ) -> Self: ...
    def style(self, style: str, **kwargs) -> Self: ...
    def __init__(self, in_channels: int = 1) -> None: ...
